<a href="https://colab.research.google.com/github/pichimalokam123/cric/blob/main/Netflix_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy
!pip install pandas
!pip install plotly.express
!pip install textblob

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting plotly.express
  Downloading plotly_express-0.4.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (2.2.2)
Requirement already satisfied: plotly>=4.1.0 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (5.24.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (0.14.4)
Requirement already satisfied: scipy>=0.18 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (1.15.3)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (1.0.1)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.11/dist-packages (from plotly.express) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.20.0->plotly.express) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.20.0->plotly.express) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.20.0->plotly.express) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.1.0->plotly.express) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.1.0->plotly.express) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly.express) (1.17.0)
Downloading plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Installing collected packages: plotly.express
Successfully installed plotly.express-0.4.1
Requirement already satisfied: textblob in /usr/local/lib/python3.11/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.11/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>=3.9->textblob) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk>=3.9->textblob) (4.67.1)

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
from textblob import TextBlob

df=pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
x=df.groupby(['rating']).size().reset_index(name='counts')
fig=px.pie(x,values='counts',names='rating',title='Distribution of Ratings')
fig.show()

In [5]:
df['director']=df['director'].fillna('Director Not Specified')
director_list=pd.DataFrame()
director_list=df['director'].str.split(',',expand=True).stack()
director_list=director_list.to_frame()
director_list.columns=['Director']
director_list

                      Director
0    0         Kirsten Johnson
1    0  Director Not Specified
2    0         Julien Leclercq
3    0  Director Not Specified
4    0  Director Not Specified
...                        ...
8802 0           David Fincher
8803 0  Director Not Specified
8804 0         Ruben Fleischer
8805 0            Peter Hewitt
8806 0             Mozez Singh

[9612 rows x 1 columns]

In [6]:
directors=director_list.groupby(['Director']).size().reset_index(name='Total Count')
directors=directors[directors.Director !='Director Not Specified']
directors=directors.sort_values(by=['Total Count'],ascending=False)
Top5directors=directors.head()
Top5directors=Top5directors.sort_values(by=['Total Count'])
fig=px.bar(Top5directors,x='Total Count',y='Director',title='Top 5 Directors')
fig.show()

In [7]:
df['cast']=df['cast'].fillna('Cast Not Specified')
cast_list=pd.DataFrame()
cast_list=df['cast'].str.split(',',expand=True).stack()
cast_list=cast_list.to_frame()
cast_list.columns=['Actor']
actors=cast_list.groupby(['Actor']).size().reset_index(name='Total Count')
actors=actors[actors.Actor !='Cast Not Specified']
actors=actors.sort_values(by=['Total Count'],ascending=False)
Top5Actors=actors.head()
Top5Actors=Top5Actors.sort_values(by=['Total Count'])
fig=px.bar(Top5Actors,x='Total Count',y='Actor',title='Top 5 Actors On Netflix')
fig.show()

Analyzing The Content Produced On Netflix Based On Years

In [9]:
df1=df[['type', 'release_year']]
df1=df1.rename(columns={'release_year':'Release Year','type': 'Type'})
df2=df1.groupby(['Release Year','Type']).size().reset_index(name='Total Count')
df2=df2[df2['Release Year']>=2005]
fig=px.line(df2,x='Release Year',y='Total Count',color='Type',title='Content Produced On Netflix Based On Years')
fig.show()

Sentiment Analysis Of Netflix Content

In [11]:
df3=df[['release_year','description']]
df3=df3.rename(columns={'release_year':'Release Year','description':'Description'})
for index, row in df3.iterrows():
  d=row['Description']
  testimonial=TextBlob(d)
  p=testimonial.sentiment.polarity
  if p==0:
    sent='Neutral'
  elif p>0:
    sent='Positive'
  else:
    sent='Negative'
  df3.loc[[index,2],'Sentiment']=sent
df3=df3.groupby(['Release Year','Sentiment']).size().reset_index(name='Total Count')
df3=df3[df3['Release Year']>2010]
fig=px.bar(df3,x='Release Year',y='Total Count',color='Sentiment',title='Sentiment Analysis Of Netflix Content')
fig.show()